;;; mcp-http-test.el --- Tests for mcp HTTP transport -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'mcp)
(require 'mcp-http)

(defun mcp-http-test--connection (&optional oauth transport)
  (make-instance 'mcp-http-process-connection :name "test" :process 'empty
                 :connection-type 'http :host "mcp.example.test" :port 443 :tls t
                 :path "/mcp" :token nil :oauth oauth :transport (or transport 'streamable) :timeout 1))

(ert-deftest mcp-http-test-parses-multiple-and-multiline-sse-events ()
  (let ((received nil) (connection (mcp-http-test--connection)))
    (cl-letf (((symbol-function 'jsonrpc-connection-receive)
               (lambda (_ message) (push message received))))
      (mcp-http--body-json connection "text/event-stream"
                           "data: {\"jsonrpc\":\"2.0\",\ndata: \"id\":1}\n\ndata: {\"jsonrpc\":\"2.0\",\"id\":2}\n\n")
      (should (equal (mapcar (lambda (m) (plist-get m :id)) (nreverse received)) '(1 2))))))

(ert-deftest mcp-http-test-crlf-response-boundary ()
  (with-temp-buffer
    (insert "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"id\":1}")
    (should (= (mcp-http--header-end)
               (progn (goto-char (point-min))
                      (search-forward "\r\n\r\n"))))))

(ert-deftest mcp-http-test-http-error-carries-request-id-and-notification-does-not-reply ()
  (let ((received nil) (connection (mcp-http-test--connection)))
    (cl-letf (((symbol-function 'jsonrpc-connection-receive) (lambda (_ message) (setq received message)))
              ((symbol-function 'jsonrpc--warn) (lambda (&rest _) nil)))
      (mcp-http--http-error connection 42 500 "access_token=secret")
      (should (= (plist-get received :id) 42))
      (should-not (string-match-p "secret" (plist-get (plist-get received :error) :data)))
      (setq received nil)
      (mcp-http--http-error connection nil 500 "x")
      (should-not received))))

(ert-deftest mcp-http-test-401-retries-once-with-same-json-and-id ()
  (let ((connection (mcp-http-test--connection 'provider))
        (token "old") callbacks posts received)
    (cl-letf (((symbol-function 'mcp-oauth-token) (lambda (_) token))
              ((symbol-function 'mcp-oauth-invalidate-access-token)
               (lambda (_) (setq token nil)))
              ((symbol-function 'mcp-oauth-ensure-token)
               (lambda (_ ok _bad) (setq token "new") (funcall ok token)))
              ((symbol-function 'jsonrpc-connection-receive)
               (lambda (_ message) (setq received message)))
              ((symbol-function 'url-retrieve)
               (lambda (_ callback &rest _)
                 (push (list url-request-data
                             (cdr (assoc "Authorization"
                                         url-request-extra-headers))
                             url-max-redirections)
                       posts)
                 (push callback callbacks)
                 nil)))
      (mcp-http--post connection "{\"id\":7}" 7 nil)
      (with-temp-buffer
        (insert "HTTP/1.1 401 Unauthorized\r\n\r\n")
        (funcall (car callbacks) nil))
      (should (= (length callbacks) 2))
      (with-temp-buffer
        (insert "HTTP/1.1 401 Unauthorized\r\n\r\n")
        (funcall (car callbacks) nil))
      (should (= (length callbacks) 2))
      (should (equal (mapcar #'car posts)
                     '("{\"id\":7}" "{\"id\":7}")))
      (should (equal (mapcar #'cadr posts)
                     '("Bearer new" "Bearer old")))
      (should (equal (mapcar #'caddr posts) '(0 0)))
      (should (= (plist-get received :id) 7)))))

(ert-deftest mcp-http-test-non-2xx-never-enables-sse ()
  (let ((connection (mcp-http-test--connection)) received)
    (cl-letf (((symbol-function 'jsonrpc-connection-receive) (lambda (_ m) (setq received m))))
      (mcp-http--http-error connection 1 403 "denied")
      (should-not (mcp--sse connection))
      (should (= -32000 (plist-get (plist-get received :error) :code))))))

(ert-deftest mcp-http-test-stop-before-response-delivers-nothing ()
  (let ((connection (mcp-http-test--connection)) callback delivered)
    (cl-letf (((symbol-function 'url-retrieve) (lambda (_ cb &rest _) (setq callback cb) nil))
              ((symbol-function 'jsonrpc-connection-receive) (lambda (&rest _) (setq delivered t)))
              ((symbol-function 'jsonrpc-running-p) (lambda (_) (not (eq connection 'stopped)))))
      (mcp-http--post connection "{}" 1 nil)
      (setq connection 'stopped)
      (with-temp-buffer (insert "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"id\":1}")
                        (funcall callback nil))
      (should-not delivered))))

(ert-deftest mcp-http-test-explicit-streamable-and-oauth-select-specialized-method ()
  (let ((connection (mcp-http-test--connection nil 'streamable)) sent)
    (cl-letf (((symbol-function 'mcp-http--post) (lambda (&rest args) (setq sent args))))
      (jsonrpc-connection-send connection :method :initialize :id 9 :params nil)
      (should (= (nth 2 sent) 9)))))

(ert-deftest mcp-http-test-auto-without-oauth-delegates-legacy-sse ()
  (let ((connection (mcp-http-test--connection nil 'auto))
        legacy-called)
    (cl-letf (((symbol-function 'mcp-http--post)
               (lambda (&rest _)
                 (ert-fail "Streamable sender should not handle legacy SSE")))
              ((symbol-function 'url-retrieve)
               (lambda (&rest _)
                 (setq legacy-called t)
                 (generate-new-buffer " *mcp-legacy-test*"))))
      (jsonrpc-connection-send connection :method :initialize :id 3 :params nil)
      (should legacy-called))))

(ert-deftest mcp-http-test-stop-cancels-oauth-authorization ()
  (let* ((mcp-server-connections (make-hash-table :test #'equal))
         (connection (mcp-http-test--connection 'provider 'streamable))
         cancelled)
    (puthash "test" connection mcp-server-connections)
    (cl-letf (((symbol-function 'mcp-oauth-cancel-authorization)
               (lambda (provider) (setq cancelled provider))))
      (mcp-stop-server "test")
      (should (eq cancelled 'provider))
      (should (eq (mcp--status connection) 'stop))
      (should-not (gethash "test" mcp-server-connections)))))

(ert-deftest mcp-http-test-oauth-send-ensures-before-post ()
  (let ((connection (mcp-http-test--connection 'provider)) sent)
    (cl-letf (((symbol-function 'mcp-oauth-ensure-token) (lambda (_ ok _bad) (funcall ok "token")))
              ((symbol-function 'mcp-http--post) (lambda (&rest args) (setq sent args))))
      (jsonrpc-connection-send connection :method :initialize :id 1 :params nil)
      (should (= (nth 2 sent) 1)))))

(provide 'mcp-http-test)
